trigger:
- develop

jobs:
- job: Linux 
  strategy:
    matrix:
      Node 4:
        NODE_VERSION: '4.x'
        COVERAGE: 'false'
      Node 5:
        NODE_VERSION: '5.x'
        COVERAGE: 'false'
      Node 6:
        NODE_VERSION: '6.x'
        COVERAGE: 'false'
      Node 7:
        NODE_VERSION: '7.x'
        COVERAGE: 'false'
      Node 8:
        NODE_VERSION: '8.x'
        COVERAGE: 'false'
      Node 12:
        NODE_VERSION: '12.x'
        COVERAGE: 'true'
  continueOnError: false
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Install Node $(NODE_VERSION)'

  - script: |
      if [[ `npm -v` == 2* ]]; then npm i -g npm@3; fi
      npm install
      npm install -g grunt-cli
      node --version
      npm --version
    displayName: 'npm install'

  - script: grunt build:travis
    env:
      COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
    displayName: 'grunt build:travis'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
    condition: and(succeeded(), eq(variables['COVERAGE'], 'true'))
    displayName: 'Publish code coverage'

steps:
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from $(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- job: Windows 
  strategy:
    matrix:
      Node 6:
        NODE_VERSION: '6.x'
      Node 7:
        NODE_VERSION: '7.x'
      Node 8:
        NODE_VERSION: '8.x'
      Node 12:
        NODE_VERSION: '12.x'
  continueOnError: false
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Install Node $(NODE_VERSION)'

  - script: |
      npm install
      npm install -g grunt-cli
      node --version
      npm --version
    displayName: 'npm install'

  - script: grunt build:travis
    env:
      COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
    displayName: 'grunt build:travis'
